### ISSUE TITLE
add weather.activities

### ISSUE THREAD

**Issue by tpowellmeto** [met-office-lab/weather-bot#31]
Ability to answer questions like 'should I hang the washing out'

**Comment by tam203** [comment]
Needs some thinking about how it over laps with the 'should I take a coat' intent. 

Other examples.

Is is a good day for a run/walk/to go to the beach/mow the lawn.

On of the challenges is that precip % is very crude. Currently we've either got it for the day or per 3 hour block (I believe) and you cant do any sort of arithmetic on the 3hr blocks to get a prediction for the afternoon (for example).

**Comment by tam203** [comment]
done, waiting for release. Could be extended with extra activities.
