### ISSUE TITLE
Disable sentry when developing locally

### ISSUE THREAD

**Issue by jacobtomlinson** [met-office-lab/weather-bot#38]
Local development should not trigger alerts in sentry. Perhaps a check for an env var of `ENVIRONMENT=production` or similar and the setting of that var in the docker compose file would be best.

**Comment by jacobtomlinson** [comment]
Maybe [here](https://github.com/met-office-lab/weather-bot/blob/9203b51a722588752ccc69312e64e2eda7ee6ee7/src/main/js/app.js#L161).

```
if (process.env.ENVIRONMENT == "production") {
    raven.context(function() {
        main();
    });
} else {
     main();
}
```

**Comment by tam203** [comment]
Done. Waiting to deploy next week.
