### ISSUE TITLE
Place doesn't parse postcodes

### ISSUE THREAD

**Issue by niallrobinson** [met-office-lab/weather-bot#48]
Should I go for a run later
Where are you planing on doing that?
EX54QZ
Hum up to you, it’s more likely than not to be dry today in Ex but it could get wet on you.

**Comment by tam203** [comment]
Dup #40

**Comment by tam203** [comment]
Useful site for testing https://www.doogal.co.uk/PostcodeGenerator.php

**Comment by tam203** [comment]
Pull request open #60
