### ISSUE TITLE
Doesn't handle dates in the dd/mm/yy format well

### ISSUE THREAD

**Issue by tam203** [met-office-lab/weather-bot#49]
![image](https://user-images.githubusercontent.com/1567535/29028957-ded880ae-7b7d-11e7-9539-9a20df2783f8.png)

Don't know if this is Sol or LUIS issue.

**Comment by tam203** [comment]
Turns out to be annoying. Its easy to start recognising dd/mm/yy just put some examples in the LUIS utterances. LUIS datetimeV2 will automatically pick it out as a date. However, it will assume US style mm/dd/yy which will then break the app in many places.

We would have to add a range of parsing in the capture stage to handle this. Look at the actual text sent for the entity and re-parse if we think it looks like a date that could of been misinterpreted.

**Comment by tpowellmeto** [comment]
Possibly raise this as a bug/improvement on the botbuilder/luis projects - ability to set some kind of locale for parsing data from text. Currently we have no control over this so I'm closing the issue.

**Comment by tam203** [comment]
Have raised - https://github.com/Microsoft/Cognitive-LUIS-Windows/issues/55 . We could do an internal fix perhaps but not worth the effort and likely fragile.
