### ISSUE TITLE
Asking for more info not aware of context

### ISSUE THREAD

**Issue by niallrobinson** [met-office-lab/weather-bot#52]
Should I go for a run today in exeter
User
Well today it’s more likely than not to be wet in Exeter. So bare that in mind.
Bot
tell me more
User
Check out the Met Office website or YouTube channel for more info.
Bot
what's the forecast
User
In Exeter on average temperatures will be around 16°C reaching a high of 17°C. Northerly winds will reach a maximum of 8mph. Visibility is expected to be good at up to 20km. There is a 84% chance of precipitation.
Bot
give me more detail
User
Check out the Met Office website or YouTube channel for more info.

**Comment by tpowellmeto** [comment]
#87
