### ISSUE TITLE
Not helpful error reply when no data

### ISSUE THREAD

**Issue by tam203** [met-office-lab/weather-bot#54]
When there is not data you get "Unfortunately there was no data to answer your question." it would be useful if there was more info. Things like:

I can't forecast beyond 5 days time
I can't tell you about the past
I got no data for Exeter on 22/10/19

And/or capture the known unanswerable before trying:

Sorry an can't give you the forecast for 'next year' as I only look 5 days into the future.

**Comment by tpowellmeto** [comment]
#71
