### ISSUE TITLE
Doesn't know about "hot" or "snow"

### ISSUE THREAD

**Issue by niallrobinson** [met-office-lab/weather-bot#56]
> Oops. Something went wrong and we need to start over.
> Bot
> Is it going to snow soon?
> User
> I’m not designed to answer that. Try asking me something I can answer.
> Bot
> it is going to be hot?
> User
> Where would you like to know that for?
> Bot
> London please
> User
> Sorry, I’m not sure I understand the weather type you’re asking about.
> Bot
> Is it going to be hot?
> User
> Sorry, I’m not sure I understand the weather type you’re asking about.

**Comment by jacobtomlinson** [comment]
Done hot in #82
